#!/bin/sh

# Install last JDK
# https://gist.github.com/rtfpessoa/17752cbf7156bdf32c59

java_base_version="8"
java_sub_version="112"
java_base_build="15"

java_version="${java_base_version}u${java_sub_version}"
java_build="b${java_base_build}"
java_version_with_build="${java_version}-${java_build}"

wget --no-cookies --header "Cookie: gpw_e24=xxx; oraclelicense=accept-securebackup-cookie;" "http://download.oracle.com/otn-pub/java/jdk/${java_version_with_build}/jdk-${java_version}-linux-x64.rpm"

sudo rpm -i jdk-${java_version}-linux-x64.rpm
rm -f jdk-${java_version}-linux-x64.rpm
